version: '3'

services:
  database:
    image: mysql
    container_name: database
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  server:
    image: php
    restart: always
    container_name: server
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    depends_on:
      - database
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
